### ISSUE TITLE
问题答错次数达到上限时机器人无法踢出

### ISSUE THREAD

**Issue by Cicini** [mzdluo123/SimpleGroupAuth#1]
已设置管理员
插件版本为最新
核心版本2.7-M2
```
2021-08-24 14:20:45 W/stderr: Exception in thread "DefaultDispatcher-worker-4" java.lang.RuntimeException: Exception while trying to handle coroutine exception
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:29)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:192)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
2021-08-24 14:20:45 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-08-24 14:20:45 W/stderr:   Suppressed: net.mamoe.mirai.contact.PermissionDeniedException: `kick` operation requires a higher permission, while MEMBER < MEMBER
2021-08-24 14:20:45 W/stderr:           at net.mamoe.mirai.internal.contact.NormalMemberImplKt.checkBotPermissionHigherThanThis(NormalMemberImpl.kt:234)
2021-08-24 14:20:45 W/stderr:           at net.mamoe.mirai.internal.contact.NormalMemberImpl.kick(NormalMemberImpl.kt:174)
2021-08-24 14:20:45 W/stderr:           at win.rainchan.simplegroupauth.EventListener$kickWrongAnswer$2.invokeSuspend(EventListener.kt:94)
2021-08-24 14:20:45 W/stderr:           at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-08-24 14:20:45 W/stderr:           ... 5 more
2021-08-24 14:20:45 W/stderr: Caused by: java.lang.IllegalStateException: 未找到异常处理器. 请继承 SimpleListenerHost 中的 handleException 方法, 或在构造 SimpleListenerHost 时提供 CoroutineExceptionHandler
2021-08-24 14:20:45 W/stderr: ------------
2021-08-24 14:20:45 W/stderr: Cannot find exception handler from coroutineContext. 
2021-08-24 14:20:45 W/stderr: Please extend SimpleListenerHost.handleException or provide a CoroutineExceptionHandler to the constructor of SimpleListenerHost
2021-08-24 14:20:45 W/stderr:   at net.mamoe.mirai.event.SimpleListenerHost.handleException(JvmMethodListeners.kt:192)
2021-08-24 14:20:45 W/stderr:   at net.mamoe.mirai.event.SimpleListenerHost$special$$inlined$CoroutineExceptionHandler$1.handleException(CoroutineExceptionHandler.kt:111)
2021-08-24 14:20:45 W/stderr:   at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:25)
2021-08-24 14:20:45 W/stderr:   ... 12 more
2021-08-24 14:20:45 W/stderr: Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.contact.PermissionDeniedException: `kick` operation requires a higher permission, while MEMBER < MEMBER]
```

**Comment by mzdluo123** [comment]
Suppressed: net.mamoe.mirai.contact.PermissionDeniedException: `kick` operation requires a higher permission, while MEMBER < MEMBER

bot需要管理员权限

**Comment by Cicini** [comment]
> Suppressed: net.mamoe.mirai.contact.PermissionDeniedException: `kick` operation requires a higher permission, while MEMBER < MEMBER
> 
> bot需要管理员权限

出现该错误前已设置管理员

**Comment by Cicini** [comment]
![QQ截图20210824195601](https://user-images.githubusercontent.com/62730438/130612805-6807e9bb-3b61-4741-8667-25a33c9d0bd6.png)
![QQ截图20210824195608](https://user-images.githubusercontent.com/62730438/130612816-86102434-c284-4314-978b-3c96aabfe5d8.png)
刚刚重新测试了一遍
报错信息相同

**Comment by mzdluo123** [comment]
可能是mirai的问题，需要提供更多信息

**Comment by Cicini** [comment]
> 可能是mirai的问题，需要提供更多信息

可能，刚刚回退旧版本也无法完成踢出操作
Mirai Console v2.7-M2
暂未发现其他报错信息

**Comment by mzdluo123** [comment]
更新
